export enum Permission {
  USER_CREATE = "USER_CREATE",
  USER_READ = "USER_READ",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  ROLE_CREATE = "ROLE_CREATE",
  ROLE_READ = "ROLE_READ",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",

  APP_SETTING_UPDATE = "APP_SETTING_UPDATE",
}
