export enum TenderStatus {
  DRAFT = 'DRAFT',
  PENDING_MD_TAGGING = 'PENDING_MD_TAGGING',
  READY_FOR_NIT = 'READY_FOR_NIT',
  MD_TAGGED = 'MD_TAGGED',
  REJECTED = 'REJECTED',
  NIT_UPLOADED = 'NIT_UPLOADED',
  NIT_VERIFIED = 'NIT_VERIFIED',
  DOCS_UPLOADED = 'DOCS_UPLOADED',
  READY_TO_MAIL = 'READY_TO_MAIL',
  MAIL_SENT = 'MAIL_SENT',
}
