export enum VendorStatus {
  NEW = 'NEW',
  INTERESTED = 'INTERESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  PENDING_MD_APPROVAL = 'PENDING_MD_APPROVAL',
  APPROVED = 'APPROVED',
  FINAL = 'FINAL',
  DELETED = 'DELETED',
  BLACKLISTED = 'BLACKLISTED',
}
